CREATE SCHEMA IF NOT EXISTS STEAM;
SET SCHEMA STEAM;
CREATE TABLE IF NOT EXISTS GAME_INFO (
    APP_ID  INTEGER NOT NULL,
    NAME    VARCHAR(255),
    TOTAL_PLAYTIME  INTEGER,
    ACHIEVEMENTS    VARCHAR(255),
    IMAGE_ICON  VARCHAR(255)
);