CREATE SCHEMA IF NOT EXISTS STEAM;
SET SCHEMA STEAM;
CREATE TABLE IF NOT EXISTS USER_INFO (
    STEAM_ID    INTEGER NOT NULL,
    USERNAME    VARCHAR(255),
    PRIMARY KEY(STEAM_ID)
);

CREATE TABLE IF NOT EXISTS GAME_INFO (
    APP_ID  INTEGER NOT NULL,
    NAME    VARCHAR(255),
    TOTAL_PLAYTIME  INTEGER,
    ACHIEVEMENTS    VARCHAR(255),
    IMAGE_ICON  VARCHAR(255),
    RATING  VARCHAR(255),
    STEAM_ID INTEGER,
    FOREIGN KEY (STEAM_ID) REFERENCES USER_INFO(STEAM_ID)
);